# Generated by Django 6.0.7 on 2026-07-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_appointment_cap', models.PositiveIntegerField(blank=True, help_text='Máximo de citas activas por mes para pacientes de esta EPS. Vacío = sin tope.', null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto mensual disponible para citas de esta EPS. Vacío = sin control.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'EPS',
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
